services:
  - type: web
    name: eventpass
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && gunicorn eventpass.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level info"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: eventpass-db
          property: connectionString
    autoDeploy: false

databases:
  - name: eventpass-db
    databaseName: eventpass_db
    user: eventpass_user
    plan: free
