# Generated by Django 4.2.30 on 2026-06-11 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='event_logos/')),
                ('registration_url', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BadgeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='badge_backgrounds/')),
                ('name_x', models.PositiveIntegerField(default=0)),
                ('name_y', models.PositiveIntegerField(default=0)),
                ('company_x', models.PositiveIntegerField(default=0)),
                ('company_y', models.PositiveIntegerField(default=0)),
                ('job_title_x', models.PositiveIntegerField(default=0)),
                ('job_title_y', models.PositiveIntegerField(default=0)),
                ('qr_x', models.PositiveIntegerField(default=0)),
                ('qr_y', models.PositiveIntegerField(default=0)),
                ('qr_size', models.PositiveIntegerField(default=150, help_text='QR code size in pixels')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge_template', to='core.event')),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('badge_color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('badge_tag', models.CharField(blank=True, max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_types', to='core.event')),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('is_checked_in', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('badge_printed', models.BooleanField(default=False)),
                ('badge_print_count', models.PositiveIntegerField(default=0)),
                ('attendee_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendees', to='core.attendeetype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='core.event')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
