# Generated by Django 4.2.30 on 2026-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='badge_pdf',
            field=models.FileField(blank=True, null=True, upload_to='badges/'),
        ),
    ]
