# Generated by Django 4.2.30 on 2026-06-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendee_badge_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetemplate',
            name='font_family',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Arial Bold', 'Arial Bold'), ('Times New Roman', 'Times New Roman'), ('Courier New', 'Courier New'), ('Verdana', 'Verdana')], default='Arial', max_length=50),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='font_size',
            field=models.PositiveIntegerField(default=36, help_text='Font size for attendee name (px)'),
        ),
        migrations.AddField(
            model_name='badgetemplate',
            name='text_color',
            field=models.CharField(default='#000000', help_text='Hex color, e.g. #000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='company_x',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='company_y',
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='job_title_x',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='job_title_y',
            field=models.PositiveIntegerField(default=220),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='name_x',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='name_y',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='qr_x',
            field=models.PositiveIntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='badgetemplate',
            name='qr_y',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
